# Generated by Django 5.0.6 on 2024-06-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoinfo',
            options={},
        ),
        migrations.RenameField(
            model_name='salidaalmacen',
            old_name='producto',
            new_name='productos',
        ),
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='payload',
        ),
    ]
