# Generated by Django 5.0.6 on 2024-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_productoinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='productos',
        ),
        migrations.AddField(
            model_name='salidaalmacen',
            name='productos',
            field=models.ManyToManyField(to='inventario.producto'),
        ),
    ]
