# Generated by Django 5.0.6 on 2024-06-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_salidaalmacen_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.AddField(
            model_name='user',
            name='punto_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.puntoventa'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='productos',
            field=models.ManyToManyField(to='inventario.producto'),
        ),
    ]
