# Generated by Django 5.0.6 on 2024-09-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='productos',
        ),
        migrations.AddField(
            model_name='producto',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.salidaalmacen'),
        ),
    ]
