# Generated by Django 5.0.6 on 2024-09-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_salidaalmacen_productos_producto_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinfo',
            name='pago_trabajador',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
