# Generated by Django 5.0.6 on 2024-06-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='productos',
            field=models.JSONField(default=dict),
        ),
    ]
