# Generated by Django 5.0.6 on 2024-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_productoinfo_pago_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
    ]
