# Generated by Django 5.0.6 on 2024-10-07 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_ventas_efectivo_ventas_transferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaalmacen',
            name='area_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.areaventa'),
        ),
    ]
