# Generated by Django 5.0.6 on 2024-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_salidaalmacen_area_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen_revoltosa',
            field=models.BooleanField(default=False),
        ),
    ]
