# Generated by Django 5.0.6 on 2024-10-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_salidaalmacenrevoltosa_producto_salida_revoltosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.salidaalmacen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='salida_revoltosa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.salidaalmacenrevoltosa'),
        ),
    ]
