# Generated by Django 5.0.6 on 2024-10-20 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_producto_salida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_remitente', to='inventario.areaventa')),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_destino', to='inventario.areaventa')),
                ('productos', models.ManyToManyField(to='inventario.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
    ]
