# Generated by Django 5.0.6 on 2024-10-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIJO', 'Fijo'), ('VARIABLE', 'Variable')], max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=10)),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
