# Generated by Django 5.0.6 on 2024-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('VARIABLE', 'Variable')], max_length=30),
        ),
    ]
