# Generated by Django 5.0.6 on 2024-10-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_gastos_frecuencia_alter_gastos_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salario',
        ),
    ]
