# Generated by Django 5.0.6 on 2024-10-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_delete_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='area_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.areaventa'),
            preserve_default=False,
        ),
    ]
