# Generated by Django 5.0.6 on 2024-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_gastos_area_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('LUNES_SABADO', 'Lunes-Sábado'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=30, null=True),
        ),
    ]
