# Generated by Django 5.0.6 on 2024-11-25 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_gastos_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen_cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='almacen',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('CAFETERIA', 'Cafetería'), ('REVOLTOSA', 'Revoltosa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='metodo_pago',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.entradaalmacen'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
        migrations.CreateModel(
            name='EntradaAlmacenCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('FIJO', 'Fijo'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(max_length=30)),
                ('comprador', models.CharField(max_length=30)),
                ('info_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoinfo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaAlmacenCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('info_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoinfo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
