# Generated by Django 5.0.6 on 2024-12-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_producto_almacen_cafeteria_user_almacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('BPA', 'BPA'), ('BANDEC', 'Bandec')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tarjetas')),
            ],
        ),
        migrations.CreateModel(
            name='TrnsferenciasTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=50)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tarjetas')),
            ],
        ),
    ]
