# Generated by Django 5.0.6 on 2024-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_tarjetas_balancetarjetas_trnsferenciastarjetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetarjetas',
            name='tarjeta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='inventario.tarjetas'),
        ),
    ]
