# Generated by Django 5.0.6 on 2024-12-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_balancetarjetas_tarjeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrnsferenciasTarjetas',
            new_name='TransferenciasTarjetas',
        ),
    ]
