# Generated by Django 5.0.6 on 2024-12-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_rename_trnsferenciastarjetas_transferenciastarjetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastarjetas',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciastarjetas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
