# Generated by Django 5.0.6 on 2024-12-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_transferenciastarjetas_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastarjetas',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas'),
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entradaalmacencafeteria',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30),
        ),
    ]
