# Generated by Django 5.0.6 on 2024-12-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_transferenciastarjetas_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciastarjetas',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas'),
        ),
    ]
