# Generated by Django 5.0.6 on 2024-12-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_transferenciastarjetas_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ALMACENERO', 'Almacenero'), ('VENDEDOR', 'Vendedor'), ('SUPERVISOR', 'Supervisor')], max_length=30),
        ),
        migrations.CreateModel(
            name='Ingrediente_Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Elaboraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mano_obra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingredientes_cantidad', models.ManyToManyField(to='inventario.ingrediente_cantidad')),
            ],
        ),
    ]
