# Generated by Django 5.0.6 on 2024-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_alter_user_rol_ingrediente_cantidad_elaboraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboraciones',
            name='nombre',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
