# Generated by Django 5.0.6 on 2024-12-20 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_elaboraciones_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='salidaalmacencafeteria',
            name='info_producto',
        ),
        migrations.RemoveField(
            model_name='salidaalmacencafeteria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ingrediente_cantidad',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen_cafeteria',
        ),
        migrations.CreateModel(
            name='Elaboraciones_Ventas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.elaboraciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Producto_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente_cantidad',
            name='ingrediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Productos_Entradas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30)),
                ('proveedor', models.CharField(max_length=30)),
                ('comprador', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(to='inventario.productos_entradas_cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Ventas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=30)),
                ('elaboraciones', models.ManyToManyField(to='inventario.elaboraciones_ventas_cafeteria')),
                ('productos', models.ManyToManyField(to='inventario.productos_ventas_cafeteria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EntradaAlmacenCafeteria',
        ),
        migrations.DeleteModel(
            name='SalidaAlmacenCafeteria',
        ),
    ]
