# Generated by Django 5.0.6 on 2024-12-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_productos_cafeteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_entradas_cafeteria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria'),
        ),
    ]
