# Generated by Django 5.0.6 on 2024-12-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_productos_entradas_cafeteria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_cafeteria',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ventas_cafeteria',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
