# Generated by Django 5.0.6 on 2024-12-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_ventas_cafeteria_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastarjetas',
            name='venta_cafeteria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas_cafeteria'),
        ),
    ]
