# Generated by Django 5.0.6 on 2024-12-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_transferenciastarjetas_venta_cafeteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaboraciones_ventas_cafeteria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elaboraciones'),
        ),
    ]
