# Generated by Django 5.0.6 on 2024-12-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_alter_inventario_producto_cafeteria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_ventas_cafeteria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria'),
        ),
    ]
