# Generated by Django 5.0.6 on 2024-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_alter_productos_ventas_cafeteria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_ventas_cafeteria',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
