# Generated by Django 5.0.6 on 2024-12-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_alter_productos_ventas_cafeteria_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto_cafeteria',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.productos_cafeteria'),
        ),
    ]
