# Generated by Django 5.0.6 on 2025-01-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_alter_inventario_producto_cafeteria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='is_cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='area_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.areaventa'),
        ),
    ]
