# Generated by Django 5.0.6 on 2025-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_gastos_is_cafeteria_alter_gastos_area_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente_cantidad',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
