# Generated by Django 5.0.6 on 2025-01-11 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_alter_ingrediente_cantidad_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario_Producto_Cafeteria',
            new_name='Inventario_Almacen_Cafeteria',
        ),
        migrations.CreateModel(
            name='Inventario_Area_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_area', to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Salidas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='inventario.productos_salidas_cafeteria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
