# Generated by Django 5.0.6 on 2025-01-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_rename_inventario_producto_cafeteria_inventario_almacen_cafeteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_almacen_cafeteria',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_almacen', to='inventario.productos_cafeteria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ALMACENERO', 'Almacenero'), ('VENDEDOR', 'Vendedor'), ('VENDEDOR CAFETERÍA', 'Vendedor Cafetería'), ('SUPERVISOR', 'Supervisor')], max_length=30),
        ),
    ]
