# Generated by Django 5.0.6 on 2025-01-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_alter_inventario_almacen_cafeteria_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas_cafeteria',
            name='productos',
            field=models.ManyToManyField(blank=True, to='inventario.productos_salidas_cafeteria'),
        ),
        migrations.CreateModel(
            name='Elaboraciones_Salidas_Almacen_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.AddField(
            model_name='salidas_cafeteria',
            name='elaboraciones',
            field=models.ManyToManyField(blank=True, to='inventario.elaboraciones_salidas_almacen_cafeteria'),
        ),
    ]
