# Generated by Django 5.0.6 on 2025-01-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_alter_salidas_cafeteria_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaboraciones_salidas_almacen_cafeteria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elaboraciones'),
        ),
    ]
