# Generated by Django 5.0.6 on 2025-01-18 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_alter_elaboraciones_salidas_almacen_cafeteria_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaventa',
            options={'verbose_name': 'Área de Venta', 'verbose_name_plural': 'Áreas de Venta'},
        ),
        migrations.AlterModelOptions(
            name='inventario_almacen_cafeteria',
            options={'verbose_name': 'Inventario Almacén Cafetería', 'verbose_name_plural': 'Inventario Almacén Cafetería'},
        ),
        migrations.AlterModelOptions(
            name='inventario_area_cafeteria',
            options={'verbose_name': 'Inventario Area Cafetería', 'verbose_name_plural': 'Inventario Area Cafetería'},
        ),
        migrations.CreateModel(
            name='CuentaCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elaboraciones', models.ManyToManyField(blank=True, to='inventario.elaboraciones')),
                ('productos', models.ManyToManyField(blank=True, to='inventario.productos_cafeteria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MermaCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elaboraciones', models.ManyToManyField(blank=True, to='inventario.elaboraciones')),
                ('productos', models.ManyToManyField(blank=True, to='inventario.productos_cafeteria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
