# Generated by Django 5.0.6 on 2025-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_alter_areaventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacasa',
            name='is_almacen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mermacafeteria',
            name='is_almacen',
            field=models.BooleanField(default=False),
        ),
    ]
