# Generated by Django 5.0.6 on 2025-01-18 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_cuentacasa_is_almacen_mermacafeteria_is_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mermacafeteria',
            options={'verbose_name': 'Merma', 'verbose_name_plural': 'Merma'},
        ),
        migrations.CreateModel(
            name='Elaboraciones_Cantidad_Cuenta_Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elaboraciones')),
            ],
        ),
        migrations.AlterField(
            model_name='cuentacasa',
            name='elaboraciones',
            field=models.ManyToManyField(blank=True, to='inventario.elaboraciones_cantidad_cuenta_casa'),
        ),
        migrations.CreateModel(
            name='Elaboraciones_Cantidad_Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elaboraciones')),
            ],
        ),
        migrations.AlterField(
            model_name='mermacafeteria',
            name='elaboraciones',
            field=models.ManyToManyField(blank=True, to='inventario.elaboraciones_cantidad_merma'),
        ),
        migrations.CreateModel(
            name='Productos_Cantidad_Cuenta_Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.AlterField(
            model_name='cuentacasa',
            name='productos',
            field=models.ManyToManyField(blank=True, to='inventario.productos_cantidad_cuenta_casa'),
        ),
        migrations.CreateModel(
            name='Productos_Cantidad_Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
            ],
        ),
        migrations.AlterField(
            model_name='mermacafeteria',
            name='productos',
            field=models.ManyToManyField(blank=True, to='inventario.productos_cantidad_merma'),
        ),
    ]
