# Generated by Django 5.0.6 on 2025-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_alter_mermacafeteria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('codigo_referido', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
