# Generated by Django 5.0.6 on 2025-03-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_cuentas_alter_balancetarjetas_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetarjetas',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='inventario.cuentas'),
        ),
        migrations.AlterField(
            model_name='transferenciastarjetas',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentas'),
        ),
    ]
