# Generated by Django 5.0.6 on 2025-03-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_alter_balancetarjetas_cuenta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceTarjetas',
        ),
    ]
