# Generated by Django 5.0.6 on 2025-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_delete_balancetarjetas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferenciasTarjetas',
            new_name='Transacciones',
        ),
    ]
