# Generated by Django 5.0.6 on 2025-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_rename_transferenciastarjetas_transacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='banco',
            field=models.CharField(blank=True, choices=[('BPA', 'BPA'), ('BANDEC', 'Bandec')], max_length=50, null=True),
        ),
    ]
