# Generated by Django 5.0.6 on 2025-03-31 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0051_alter_cuentas_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='venta_cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas_cafeteria'),
        ),
    ]
