# Generated by Django 5.0.6 on 2025-04-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0052_alter_transacciones_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.entradaalmacen'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='entrada_cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.entradas_cafeteria'),
        ),
    ]
