# Generated by Django 5.0.6 on 2025-04-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0053_transacciones_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=30)),
                ('no_cuenta_cup', models.CharField(max_length=30)),
                ('no_cuenta_mayorista', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='entradaalmacen',
            name='proveedor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
