# Generated by Django 5.0.6 on 2025-04-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_proveedor_alter_entradaalmacen_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacen',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
