# Generated by Django 5.0.6 on 2025-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_alter_entradaalmacen_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_no_cuenta_cup',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_no_cuenta_mayorista',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='proveedor_telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entradas_cafeteria',
            name='proveedor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
