# Generated by Django 5.0.6 on 2025-04-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0056_entradas_cafeteria_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas_cafeteria',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
