# Generated by Django 5.0.6 on 2025-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0057_alter_entradas_cafeteria_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='no_cuenta_cup',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='no_cuenta_mayorista',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
