# Generated by Django 5.0.6 on 2025-05-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0058_alter_proveedor_no_cuenta_cup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoinfo',
            name='codigo',
        ),
    ]
