# Generated by Django 5.0.6 on 2025-05-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0060_historialpreciocostosalon_historialprecioventasalon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinfo',
            name='new_precio_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.historialpreciocostosalon'),
        ),
        migrations.AddField(
            model_name='productoinfo',
            name='new_precio_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.historialprecioventasalon'),
        ),
    ]
