# Generated by Django 5.0.6 on 2025-05-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0061_productoinfo_new_precio_costo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoinfo",
            name="new_precio_costo",
        ),
        migrations.RemoveField(
            model_name="productoinfo",
            name="new_precio_venta",
        ),
    ]
