# Generated by Django 5.0.6 on 2025-05-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0062_remove_productoinfo_precio_costo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialpreciocostosalon",
            name="producto_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_costo",
                to="inventario.productoinfo",
            ),
        ),
        migrations.AddField(
            model_name="historialprecioventasalon",
            name="producto_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_venta",
                to="inventario.productoinfo",
            ),
        ),
    ]
