# Generated by Django 5.0.6 on 2025-05-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0063_add_historial_precio_costo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoinfo",
            name="precio_costo",
        ),
        migrations.RemoveField(
            model_name="productoinfo",
            name="precio_venta",
        ),
    ]
