# Generated by Django 5.0.6 on 2025-05-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0065_historialpreciocostocafeteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_cafeteria',
            name='precio_costo',
        ),
        migrations.RemoveField(
            model_name='productos_cafeteria',
            name='precio_venta',
        ),
    ]
