# Generated by Django 5.0.6 on 2025-05-21 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_remove_productos_cafeteria_precio_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioElaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('elaboracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio_elaboracion', to='inventario.elaboraciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
