# Generated by Django 5.0.6 on 2025-05-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0067_precioelaboracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioElaboracion',
        ),
    ]
