# Generated by Django 5.0.6 on 2025-05-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0069_precioelaboracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaboraciones',
            name='precio',
        ),
    ]
