# Generated by Django 5.0.6 on 2025-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0070_remove_elaboraciones_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='entradaalmacen',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
