# Generated by Django 5.0.6 on 2025-06-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0071_entradaalmacen_efectivo_entradaalmacen_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaalmacen',
            name='efectivo',
        ),
        migrations.RemoveField(
            model_name='entradaalmacen',
            name='transferencia',
        ),
    ]
