# Generated by Django 5.0.6 on 2025-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0072_remove_entradaalmacen_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaventa',
            name='isMesa',
            field=models.BooleanField(default=False),
        ),
    ]
