# Generated by Django 5.0.6 on 2025-10-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0073_areaventa_ismesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentas'),
        ),
    ]
