# Generated by Django 5.0.6 on 2025-10-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0074_gastos_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.gastos'),
        ),
    ]
