# Generated by Django 5.0.6 on 2025-10-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0075_transacciones_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='moneda',
            field=models.CharField(choices=[('CUP', 'CUP'), ('USD', 'USD')], default='CUP', max_length=3),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('VENTA', 'Venta'), ('PAGO_TRABAJADOR', 'Pago trabajador'), ('GASTO_FIJO', 'Gasto fijo'), ('GASTO_VARIABLE', 'Gasto variable'), ('TRANSFERENCIA', 'Transferencia'), ('ENTRADA', 'Entrada')], max_length=30),
        ),
    ]
