# Generated by Django 5.0.6 on 2025-10-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0076_cuentas_moneda_alter_transacciones_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaventa',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
