# Generated by Django 5.0.6 on 2025-10-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0077_areaventa_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaventa',
            name='isMesa',
        ),
        migrations.AddField(
            model_name='areaventa',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cuentas'),
        ),
    ]
