# Generated by Django 5.0.6 on 2025-10-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0078_remove_areaventa_ismesa_areaventa_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='cuenta_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentacasa'),
        ),
    ]
