# Generated by Django 5.0.6 on 2025-10-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0079_transacciones_cuenta_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaventa',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.cuentas'),
            preserve_default=False,
        ),
    ]
