# Generated by Django 5.0.6 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0080_alter_areaventa_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('LUNES_SABADO', 'Lunes-Sábado')], max_length=30, null=True),
        ),
    ]
