# Generated by Django 5.0.6 on 2025-10-31 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0081_gastos_is_general_alter_gastos_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='areas_venta',
            field=models.ManyToManyField(blank=True, to='inventario.areaventa'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='area_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastosparaborrar', to='inventario.areaventa'),
        ),
    ]
