# Generated by Django 5.0.6 on 2025-11-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0083_remove_gastos_area_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='is_general',
        ),
    ]
