# Generated by Django 5.0.6 on 2025-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0084_remove_gastos_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='moneda',
            field=models.CharField(choices=[('CUP', 'CUP'), ('USD', 'USD')], default='CUP', max_length=3),
        ),
    ]
