# Generated by Django 5.0.6 on 2025-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0085_transacciones_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
