# Generated by Django 5.0.6 on 2025-11-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0086_alter_transacciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpreciocostocafeteria',
            name='precio',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historialprecioventacafeteria',
            name='precio',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
