# Generated by Django 5.0.6 on 2025-11-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0087_alter_historialpreciocostocafeteria_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_cafeteria',
            name='is_ingrediente',
            field=models.BooleanField(default=False),
        ),
    ]
