# Generated by Django 5.0.6 on 2025-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0088_productos_cafeteria_is_ingrediente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentas',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='productos_cafeteria',
            options={'verbose_name': 'Producto de cafeteria', 'verbose_name_plural': 'Productos de cafeteria'},
        ),
        migrations.AlterField(
            model_name='ingrediente_cantidad',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventario_almacen_cafeteria',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventario_area_cafeteria',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
