# Generated by Django 5.0.6 on 2025-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0089_alter_cuentas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_cafeteria',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
