# Generated by Django 5.0.6 on 2025-11-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0090_productos_cafeteria_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacciones',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transacciones',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='inventario.cuentas'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='inventario.cuentas'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
