# Generated by Django 5.0.6 on 2025-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0091_alter_transacciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
