# Generated by Django 5.0.6 on 2026-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0092_cuentas_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinfo',
            name='localizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCARIA', 'Bancaria'), ('ZELLE', 'Zelle')], max_length=30),
        ),
    ]
