# Generated by Django 5.0.6 on 2026-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0093_productoinfo_localizacion_alter_cuentas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
