# Generated by Django 5.0.6 on 2026-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0094_cuentas_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='is_cuenta_fiscal',
            field=models.BooleanField(default=False),
        ),
    ]
