# Generated by Django 5.0.6 on 2026-02-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0095_cuentas_is_cuenta_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
