# Generated by Django 5.0.6 on 2026-02-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0096_transacciones_saldo_resultante'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='saldo_resultante_origen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
