# Generated by Django 5.0.6 on 2026-02-20 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0097_transacciones_saldo_resultante_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSaldoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_saldos', to='inventario.cuentas')),
            ],
            options={
                'verbose_name': 'Historial de saldo de cuenta',
                'verbose_name_plural': 'Historial de saldos de cuentas',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='historialsaldocuenta',
            constraint=models.UniqueConstraint(fields=('cuenta', 'fecha'), name='unique_historial_saldo_cuenta_fecha'),
        ),
    ]
