# Generated by Django 5.0.6 on 2026-03-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0098_historialsaldocuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCARIA', 'Bancaria'), ('ZELLE', 'Zelle'), ('CUENTA_POR_PAGAR', 'Cuenta por pagar'), ('PAGO_ANTICIPADO', 'Pago anticipado')], max_length=30),
        ),
        migrations.AddField(
            model_name='gastos',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.conceptogasto'),
        ),
    ]
