# Generated by Django 5.0.6 on 2026-03-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0099_conceptogasto_alter_cuentas_tipo_gastos_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_cafeteria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('INGREDIENTE', 'Ingrediente'), ('REVENTA', 'Reventa')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productos_cafeteria',
            name='unidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conceptogasto',
            name='emoji',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ALMACEN', 'Almacén'), ('CENTRO_DE_ELABORACION', 'Centro de elaboración'), ('PUNTO_DE_VENTA', 'Punto de venta')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('cuenta_para_efectivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.cuentas')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos_cafeteria')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicaciones')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
