# Generated by Django 5.0.6 on 2026-03-23 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0100_productos_cafeteria_tipo_productos_cafeteria_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicaciones'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('producto', 'ubicacion'), name='inventario_prod_ubica_unique'),
        ),
    ]
