# Generated by Django 5.0.6 on 2026-03-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0101_alter_inventario_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas_cafeteria',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicaciones'),
        ),
    ]
