# Generated by Django 5.0.6 on 2026-03-24 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0102_salidas_cafeteria_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboraciones_ventas_cafeteria',
            name='centro_elaboracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicaciones'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='tipo',
            field=models.CharField(choices=[('ALMACEN', 'Almacén'), ('CENTRO_ELABORACION', 'Centro de elaboración'), ('POS', 'Punto de venta')], max_length=30),
        ),
    ]
