# Generated by Django 5.0.6 on 2026-03-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0103_elaboraciones_ventas_cafeteria_centro_elaboracion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MermaCafeteria',
            new_name='Merma',
        ),
        migrations.AlterModelOptions(
            name='merma',
            options={'verbose_name': 'Merma', 'verbose_name_plural': 'Mermas'},
        ),
        migrations.AddField(
            model_name='producto',
            name='merma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_dados_baja', to='inventario.merma'),
        ),
    ]