# Generated by Django 5.0.6 on 2026-03-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0104_merma_producto_merma_delete_mermacafeteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicaciones'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='merma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.merma'),
        ),
    ]
