# Generated by Django 5.0.6 on 2026-04-02 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0105_merma_ubicacion_alter_producto_merma'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.areaventa'),
        ),
    ]
