# Generated by Django 5.0.6 on 2026-04-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0106_merma_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_area_cafeteria',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Inventario_Almacen_Cafeteria',
        ),
        migrations.DeleteModel(
            name='Inventario_Area_Cafeteria',
        ),
    ]
