# Generated by Django 5.0.6 on 2026-04-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0107_remove_inventario_area_cafeteria_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merma',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MERMA', 'Merma'), ('CUENTA_CASA', 'Cuenta Casa'), ('ERROR', 'Error')], max_length=50, null=True),
        ),
    ]
