# Generated by Django 5.0.6 on 2026-04-05 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0108_merma_descripcion_merma_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='merma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.merma'),
        ),
    ]
