# Generated by Django 5.0.6 on 2026-04-22 00:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0110_historialrecetaelaboracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacen',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto'), ('DEUDA', 'Deuda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entradas_cafeteria',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto'), ('DEUDA', 'Deuda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('VENTA', 'Venta'), ('PAGO_TRABAJADOR', 'Pago trabajador'), ('GASTO_FIJO', 'Gasto fijo'), ('GASTO_VARIABLE', 'Gasto variable'), ('TRANSFERENCIA', 'Transferencia'), ('ENTRADA', 'Entrada'), ('PAGO_DEUDA', 'Pago de Deuda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto'), ('DEUDA', 'Deuda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ventas_cafeteria',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto'), ('DEUDA', 'Deuda')], max_length=30),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('moneda', models.CharField(choices=[('CUP', 'CUP'), ('USD', 'USD')], default='CUP', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA_PARCIAL', 'Pagada Parcialmente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrada_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='inventario.entradaalmacen')),
                ('entrada_cafeteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='inventario.entradas_cafeteria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='inventario.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PagoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.cuentas')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.deuda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Deuda',
                'verbose_name_plural': 'Pagos de Deudas',
            },
        ),
        migrations.AddField(
            model_name='transacciones',
            name='pago_deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.pagodeuda'),
        ),
    ]
