# Generated by Django 5.0.6 on 2026-04-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0111_alter_entradaalmacen_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacasa',
            name='elaboraciones',
        ),
        migrations.RemoveField(
            model_name='cuentacasa',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='cuentacasa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='cuenta_casa',
        ),
        migrations.DeleteModel(
            name='AjusteInventario',
        ),
        migrations.DeleteModel(
            name='CuentaCasa',
        ),
    ]
