# Generated by Django 5.0.6 on 2026-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0112_remove_cuentacasa_elaboraciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_cafeteria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
