# Generated by Django 5.0.6 on 2026-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0113_alter_productos_cafeteria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinfo',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
