# Generated by Django 5.0.6 on 2026-05-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0114_alter_productoinfo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
