# Generated by Django 5.0.6 on 2026-06-07 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0115_transacciones_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSaldoInventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
            ],
        ),
    ]
