# Generated by Django 5.0.6 on 2026-06-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0116_historialsaldoinventarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsaldoinventarios',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
