# Generated by Django 5.0.6 on 2026-06-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0117_alter_historialsaldoinventarios_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_cafeteria',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_cafeteria', to='inventario.ubicaciones'),
        ),
    ]
