# Generated by Django 5.0.6 on 2026-08-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0118_ventas_cafeteria_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='es_reversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='transaccion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversiones', to='inventario.transacciones'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas_cafeteria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
