# Generated by Django 5.0.6 on 2026-08-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0119_transacciones_es_reversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas_cafeteria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
